### ISSUE TITLE
Review Replace method

### ISSUE THREAD

**Issue by IetermagogSA** [PacktPublishing/An-Atypical-ASP.NET-Core-6-Design-Patterns-Guide#18]
Hi,

Please correct me if I am mistaken, but in Ch3 explaining the Single Reponsibility Principle, the if-statement should have a not(!) operator when checking if an instance of that book exists in the list.

The current code:
    public void Replace(Book book)
    {
        if (_books.Any(x => x.Id == book.Id))
        {
            throw new Exception($"Book {book.Id} does not exist!");
        }
        var index = _books.FindIndex(x => x.Id == book.Id);
        _books[index] = book;
    }

Should be replaced with:
    public void Replace(Book book)
    {
        if (!_books.Any(x => x.Id == book.Id))
        {
            throw new Exception($"Book {book.Id} does not exist!");
        }
        var index = _books.FindIndex(x => x.Id == book.Id);
        _books[index] = book;
    }

**Comment by Carl-Hugo** [comment]
Thanks for pointing this out. You are correct; that is a mistake. I corrected the issue in the GitHub repository (see PR #19). The missing `!` comes from the first code sample, and the error is present in a few subsequent examples built on top of it.
Mistake aside, I hope you are enjoying the book so far!
